language: node_js
node_js:
  - 14
  - 12
  - 10

services:
  - docker

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d
  - cp ormconfig.travis.json ormconfig.json

script:
  - yarn --frozen-lockfile
  - yarn compile
  - yarn test
  - yarn lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
