language: node_js
node_js:
  - 14
  - 12
  - 10

services:
  - docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d
  - cp ormconfig.travis.json ormconfig.json

script:
  - npx nyc npm test
  - npm run lint
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
